import ProjectDescription
import EnvPlugin

let workspace = Workspace(
    name: workspaceEnv.name,
    projects: [
        "Projects/App"
    ],
    additionalFiles: [
        "README.md"
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
