import ProjectDescription
import EnvPlugin

let workspace = Workspace(
    name: "\(env.name)-WorkSpace",
    projects: [
        "Projects/App"
    ],
    additionalFiles: [
        "README.md"
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
